# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Production workflow

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Development Codes
      uses: actions/checkout@v2
    - name: Use Node.js 17.x
      uses: actions/setup-node@v1
      with:
          node-version: 17.x
    - run: npm install
    - run: npm test
    - run: npm run build --if-present
    - name: Deploy to Heroku
      uses: akhileshns/heroku-deploy@v3.12.12
      with:
          args: deploy --dir=build --prod
          heroku_api_key: 7738da07-fe87-4ab9-9359-1a153647190b
          heroku_app_name: 'safe-waters-76911'
          heroku_email: '123190088@student.upnyk.ac.id'
